name: Bug Report
description: Create a report to help us improve Imyra Health
title: "[BUG] "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to file a bug report! 
        **Note:** Imyra is a strictly zero-cloud application. Please do not attach screenshots that contain your sensitive personal clinical data.
  
  - type: input
    id: version
    attributes:
      label: App Version
      description: What version of Imyra Health are you using? (e.g., 1.0.0)
    validations:
      required: true
      
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: Are you using iOS or Android?
      options:
        - iOS
        - Android
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
